name: Build Eden on macOS 14 (Sonoma)

on:
  push:
    branches: [ macos ]  # 你可以改成你需要的分支
  pull_request:
    branches: [ macos ]

jobs:
  build:
    runs-on: macos-14  # 指定 macOS 14 Sonoma，相当于 mac26

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies via Homebrew
      run: |
        brew update
        brew install autoconf automake boost ffmpeg fmt glslang hidapi libtool libusb lz4 ninja nlohmann-json openssl pkg-config qt@6 sdl2 speexdsp zlib zstd cmake catch2 molten-vk vulkan-loader spirv-tools

    - name: Install Xcode command line tools
      run: xcode-select --install || true

    - name: Configure CMake
      run: |
        cmake -S . -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DYUZU_TESTS=OFF

    - name: Build
      run: |
        cmake --build build --config Release

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: eden-macos-build
        path: build/bin/  # 根据实际 Eden 可执行文件路径调整
